export const adminStats = {
    pendingSuppliers: 8,
    activeSuppliers: 142,
    totalUsers: 3547,
    abuseReports: 3,
    monthlyRevenue: 24582,
    conversionRate: 68,
    totalQuotes: 1284,
    totalRequests: 892,
  };

export const adminUsers = [
    { id: "USR-001", name: "James Wilson", email: "james.wilson@email.co.uk", location: "London, SW1A 1AA", joinedDate: "2024-09-28", role: "Driver", status: "Active" },
    { id: "USR-002", name: "Emily Thompson", email: "emily.thompson@email.co.uk", location: "Manchester, M1 1AA", joinedDate: "2024-09-27", role: "Driver", status: "Active" },
    { id: "USR-003", name: "Oliver Davis", email: "oliver.davis@email.co.uk", location: "Birmingham, B1 1AA", joinedDate: "2024-09-27", role: "Driver", status: "Active" },
    { id: "USR-004", name: "Sophie Anderson", email: "sophie.anderson@email.co.uk", location: "Liverpool, L1 1AA", joinedDate: "2024-09-26", role: "Driver", status: "Active" },
    { id: "USR-005", name: "Harry Roberts", email: "harry.roberts@email.co.uk", location: "Leeds, LS1 1AA", joinedDate: "2024-09-26", role: "Driver", status: "Suspended" },
    { id: "USR-006", name: "Amelia Clark", email: "amelia.clark@email.co.uk", location: "Bristol, BS1 1AA", joinedDate: "2024-09-25", role: "Driver", status: "Active" },
    { id: "USR-007", name: "George Martin", email: "george.martin@email.co.uk", location: "Sheffield, S1 1AA", joinedDate: "2024-09-25", role: "Driver", status: "Active" },
    { id: "USR-008", name: "Isabella White", email: "isabella.white@email.co.uk", location: "Newcastle, NE1 1AA", joinedDate: "2024-09-24", role: "Driver", status: "Active" },
    { id: "USR-009", name: "Jack Thomas", email: "jack.thomas@email.co.uk", location: "Cardiff, CF1 1AA", joinedDate: "2024-09-24", role: "Driver", status: "Active" },
    { id: "USR-010", name: "Olivia Harris", email: "olivia.harris@email.co.uk", location: "Edinburgh, EH1 1AA", joinedDate: "2024-09-23", role: "Driver", status: "Active" },
    { id: "USR-011", name: "William Turner", email: "william.turner@email.co.uk", location: "Glasgow, G1 1AA", joinedDate: "2024-09-23", role: "Driver", status: "Active" },
    { id: "USR-012", name: "Charlotte Evans", email: "charlotte.evans@email.co.uk", location: "Nottingham, NG1 1AA", joinedDate: "2024-09-22", role: "Driver", status: "Active" },
    { id: "USR-013", name: "Thomas Moore", email: "thomas.moore@email.co.uk", location: "Leicester, LE1 1AA", joinedDate: "2024-09-22", role: "Driver", status: "Suspended" },
    { id: "USR-014", name: "Mia Robinson", email: "mia.robinson@email.co.uk", location: "Southampton, SO14 1AA", joinedDate: "2024-09-21", role: "Driver", status: "Active" },
    { id: "USR-015", name: "Daniel Walker", email: "daniel.walker@email.co.uk", location: "Oxford, OX1 1AA", joinedDate: "2024-09-21", role: "Driver", status: "Active" },
    { id: "USR-016", name: "Ella Hughes", email: "ella.hughes@email.co.uk", location: "Cambridge, CB1 1AA", joinedDate: "2024-09-20", role: "Driver", status: "Active" },
    { id: "USR-017", name: "Benjamin Wright", email: "benjamin.wright@email.co.uk", location: "Portsmouth, PO1 1AA", joinedDate: "2024-09-20", role: "Driver", status: "Active" },
    { id: "USR-018", name: "Grace Taylor", email: "grace.taylor@email.co.uk", location: "York, YO1 1AA", joinedDate: "2024-09-19", role: "Driver", status: "Active" },
    { id: "USR-019", name: "Lucas Green", email: "lucas.green@email.co.uk", location: "Coventry, CV1 1AA", joinedDate: "2024-09-19", role: "Driver", status: "Active" },
    { id: "USR-020", name: "Lily Hall", email: "lily.hall@email.co.uk", location: "Brighton, BN1 1AA", joinedDate: "2024-09-18", role: "Driver", status: "Active" },
    { id: "USR-021", name: "Noah Baker", email: "noah.baker@email.co.uk", location: "Derby, DE1 1AA", joinedDate: "2024-09-18", role: "Driver", status: "Active" },
    { id: "USR-022", name: "Freya King", email: "freya.king@email.co.uk", location: "Plymouth, PL1 1AA", joinedDate: "2024-09-17", role: "Driver", status: "Suspended" },
    { id: "USR-023", name: "Ethan Scott", email: "ethan.scott@email.co.uk", location: "Swansea, SA1 1AA", joinedDate: "2024-09-17", role: "Driver", status: "Active" },
    { id: "USR-024", name: "Ava Mitchell", email: "ava.mitchell@email.co.uk", location: "Reading, RG1 1AA", joinedDate: "2024-09-16", role: "Driver", status: "Active" },
    { id: "USR-025", name: "Alexander Ward", email: "alexander.ward@email.co.uk", location: "Wolverhampton, WV1 1AA", joinedDate: "2024-09-16", role: "Driver", status: "Active" },
    { id: "USR-026", name: "Poppy Foster", email: "poppy.foster@email.co.uk", location: "Aberdeen, AB10 1AA", joinedDate: "2024-09-15", role: "Driver", status: "Active" },
    { id: "USR-027", name: "Joshua Cooper", email: "joshua.cooper@email.co.uk", location: "Stoke, ST1 1AA", joinedDate: "2024-09-15", role: "Driver", status: "Active" },
    { id: "USR-028", name: "Scarlett Reed", email: "scarlett.reed@email.co.uk", location: "Hull, HU1 1AA", joinedDate: "2024-09-14", role: "Driver", status: "Active" },
    { id: "USR-029", name: "Samuel Morgan", email: "samuel.morgan@email.co.uk", location: "Preston, PR1 1AA", joinedDate: "2024-09-14", role: "Driver", status: "Active" },
    { id: "USR-030", name: "Ruby Barnes", email: "ruby.barnes@email.co.uk", location: "Norwich, NR1 1AA", joinedDate: "2024-09-13", role: "Driver", status: "Suspended" },
    { id: "USR-031", name: "Joseph Bell", email: "joseph.bell@email.co.uk", location: "Bournemouth, BH1 1AA", joinedDate: "2024-09-13", role: "Driver", status: "Active" },
    { id: "USR-032", name: "Daisy Wood", email: "daisy.wood@email.co.uk", location: "Sunderland, SR1 1AA", joinedDate: "2024-09-12", role: "Driver", status: "Active" },
    { id: "USR-033", name: "Henry Price", email: "henry.price@email.co.uk", location: "Dundee, DD1 1AA", joinedDate: "2024-09-12", role: "Driver", status: "Active" },
    { id: "USR-034", name: "Isabelle Cox", email: "isabelle.cox@email.co.uk", location: "Exeter, EX1 1AA", joinedDate: "2024-09-11", role: "Driver", status: "Active" },
    { id: "USR-035", name: "Charlie Watson", email: "charlie.watson@email.co.uk", location: "Ipswich, IP1 1AA", joinedDate: "2024-09-11", role: "Driver", status: "Active" },
    { id: "USR-036", name: "Florence Murphy", email: "florence.murphy@email.co.uk", location: "Middlesbrough, TS1 1AA", joinedDate: "2024-09-10", role: "Driver", status: "Active" },
    { id: "USR-037", name: "Alfie Collins", email: "alfie.collins@email.co.uk", location: "Warrington, WA1 1AA", joinedDate: "2024-09-10", role: "Driver", status: "Active" },
    { id: "USR-038", name: "Evie Russell", email: "evie.russell@email.co.uk", location: "Luton, LU1 1AA", joinedDate: "2024-09-09", role: "Driver", status: "Suspended" },
    { id: "USR-039", name: "Oscar Butler", email: "oscar.butler@email.co.uk", location: "Northampton, NN1 1AA", joinedDate: "2024-09-09", role: "Driver", status: "Active" },
    { id: "USR-040", name: "Chloe Gray", email: "chloe.gray@email.co.uk", location: "Bath, BA1 1AA", joinedDate: "2024-09-08", role: "Driver", status: "Active" },
    { id: "USR-041", name: "Leo Powell", email: "leo.powell@email.co.uk", location: "Cheltenham, GL50 1AA", joinedDate: "2024-09-08", role: "Driver", status: "Active" },
    { id: "USR-042", name: "Sienna James", email: "sienna.james@email.co.uk", location: "Gloucester, GL1 1AA", joinedDate: "2024-09-07", role: "Driver", status: "Active" },
    { id: "USR-043", name: "Freddie Hayes", email: "freddie.hayes@email.co.uk", location: "Salisbury, SP1 1AA", joinedDate: "2024-09-07", role: "Driver", status: "Active" },
    { id: "USR-044", name: "Sophia Bennett", email: "sophia.bennett@email.co.uk", location: "Worcester, WR1 1AA", joinedDate: "2024-09-06", role: "Driver", status: "Active" },
    { id: "USR-045", name: "Archie Richardson", email: "archie.richardson@email.co.uk", location: "Chester, CH1 1AA", joinedDate: "2024-09-06", role: "Driver", status: "Suspended" },
    { id: "USR-046", name: "Phoebe Ross", email: "phoebe.ross@email.co.uk", location: "Blackpool, FY1 1AA", joinedDate: "2024-09-05", role: "Driver", status: "Active" },
    { id: "USR-047", name: "Max Chapman", email: "max.chapman@email.co.uk", location: "Lancaster, LA1 1AA", joinedDate: "2024-09-05", role: "Driver", status: "Active" },
    { id: "USR-048", name: "Alice Jenkins", email: "alice.jenkins@email.co.uk", location: "Durham, DH1 1AA", joinedDate: "2024-09-04", role: "Driver", status: "Active" },
    { id: "USR-049", name: "Harrison Shaw", email: "harrison.shaw@email.co.uk", location: "Carlisle, CA1 1AA", joinedDate: "2024-09-04", role: "Driver", status: "Active" },
    { id: "USR-050", name: "Millie Palmer", email: "millie.palmer@email.co.uk", location: "Lincoln, LN1 1AA", joinedDate: "2024-09-03", role: "Driver", status: "Active" },
    { id: "USR-051", name: "Sebastian Fox", email: "sebastian.fox@email.co.uk", location: "Peterborough, PE1 1AA", joinedDate: "2024-09-03", role: "Driver", status: "Active" },
    { id: "USR-052", name: "Matilda Hunt", email: "matilda.hunt@email.co.uk", location: "Canterbury, CT1 1AA", joinedDate: "2024-09-02", role: "Driver", status: "Suspended" },
    { id: "USR-053", name: "Arthur Long", email: "arthur.long@email.co.uk", location: "Winchester, SO23 1AA", joinedDate: "2024-09-02", role: "Driver", status: "Active" },
    { id: "USR-054", name: "Rosie Mills", email: "rosie.mills@email.co.uk", location: "Stirling, FK8 1AA", joinedDate: "2024-09-01", role: "Driver", status: "Active" },
    { id: "USR-055", name: "Theodore Ellis", email: "theodore.ellis@email.co.uk", location: "Inverness, IV1 1AA", joinedDate: "2024-09-01", role: "Driver", status: "Active" },
    { id: "USR-056", name: "Maya Richards", email: "maya.richards@email.co.uk", location: "Truro, TR1 1AA", joinedDate: "2024-08-31", role: "Driver", status: "Active" },
    { id: "USR-057", name: "Louis Carter", email: "louis.carter@email.co.uk", location: "Hereford, HR1 1AA", joinedDate: "2024-08-31", role: "Driver", status: "Active" },
    { id: "USR-058", name: "Violet Dixon", email: "violet.dixon@email.co.uk", location: "Shrewsbury, SY1 1AA", joinedDate: "2024-08-30", role: "Driver", status: "Active" },
    { id: "USR-059", name: "Jacob Marshall", email: "jacob.marshall@email.co.uk", location: "Bangor, LL57 1AA", joinedDate: "2024-08-30", role: "Driver", status: "Active" },
    { id: "USR-060", name: "Harriet Hunter", email: "harriet.hunter@email.co.uk", location: "Newport, NP20 1AA", joinedDate: "2024-08-29", role: "Driver", status: "Suspended" },
    { id: "USR-061", name: "Edward Webb", email: "edward.webb@email.co.uk", location: "Wrexham, LL11 1AA", joinedDate: "2024-08-29", role: "Driver", status: "Active" },
    { id: "USR-062", name: "Elsie Harvey", email: "elsie.harvey@email.co.uk", location: "Colchester, CO1 1AA", joinedDate: "2024-08-28", role: "Driver", status: "Active" },
    { id: "USR-063", name: "Finley Stevens", email: "finley.stevens@email.co.uk", location: "Chelmsford, CM1 1AA", joinedDate: "2024-08-28", role: "Driver", status: "Active" },
    { id: "USR-064", name: "Penelope Grant", email: "penelope.grant@email.co.uk", location: "Maidstone, ME14 1AA", joinedDate: "2024-08-27", role: "Driver", status: "Active" },
    { id: "USR-065", name: "Zachary Mason", email: "zachary.mason@email.co.uk", location: "Guildford, GU1 1AA", joinedDate: "2024-08-27", role: "Driver", status: "Active" },
    { id: "USR-066", name: "Jasmine Armstrong", email: "jasmine.armstrong@email.co.uk", location: "Southend, SS1 1AA", joinedDate: "2024-08-26", role: "Driver", status: "Active" },
    { id: "USR-067", name: "Liam Howard", email: "liam.howard@email.co.uk", location: "Slough, SL1 1AA", joinedDate: "2024-08-26", role: "Driver", status: "Active" },
    { id: "USR-068", name: "Esme Fuller", email: "esme.fuller@email.co.uk", location: "Basildon, SS14 1AA", joinedDate: "2024-08-25", role: "Driver", status: "Suspended" },
    { id: "USR-069", name: "Isaac Barnes", email: "isaac.barnes@email.co.uk", location: "Basingstoke, RG21 1AA", joinedDate: "2024-08-25", role: "Driver", status: "Active" },
    { id: "USR-070", name: "Layla Spencer", email: "layla.spencer@email.co.uk", location: "Crawley, RH10 1AA", joinedDate: "2024-08-24", role: "Driver", status: "Active" },
    { id: "USR-071", name: "Reuben Owen", email: "reuben.owen@email.co.uk", location: "Harrogate, HG1 1AA", joinedDate: "2024-08-24", role: "Driver", status: "Active" },
    { id: "USR-072", name: "Emilia Stone", email: "emilia.stone@email.co.uk", location: "Watford, WD17 1AA", joinedDate: "2024-08-23", role: "Driver", status: "Active" },
    { id: "USR-073", name: "Cameron Gardner", email: "cameron.gardner@email.co.uk", location: "Stevenage, SG1 1AA", joinedDate: "2024-08-23", role: "Driver", status: "Active" },
    { id: "USR-074", name: "Maisie Knight", email: "maisie.knight@email.co.uk", location: "St Albans, AL1 1AA", joinedDate: "2024-08-22", role: "Driver", status: "Active" },
    { id: "USR-075", name: "Dylan Simpson", email: "dylan.simpson@email.co.uk", location: "Hemel Hempstead, HP1 1AA", joinedDate: "2024-08-22", role: "Driver", status: "Suspended" },
    { id: "USR-076", name: "Amelie West", email: "amelie.west@email.co.uk", location: "High Wycombe, HP11 1AA", joinedDate: "2024-08-21", role: "Driver", status: "Active" },
    { id: "USR-077", name: "Adam Pearce", email: "adam.pearce@email.co.uk", location: "Aylesbury, HP20 1AA", joinedDate: "2024-08-21", role: "Driver", status: "Active" },
    { id: "USR-078", name: "Aurora Cole", email: "aurora.cole@email.co.uk", location: "Milton Keynes, MK9 1AA", joinedDate: "2024-08-20", role: "Driver", status: "Active" },
    { id: "USR-079", name: "Jude Duncan", email: "jude.duncan@email.co.uk", location: "Wigan, WN1 1AA", joinedDate: "2024-08-20", role: "Driver", status: "Active" },
    { id: "USR-080", name: "Arabella Holmes", email: "arabella.holmes@email.co.uk", location: "Bolton, BL1 1AA", joinedDate: "2024-08-19", role: "Driver", status: "Active" },
    { id: "USR-081", name: "Felix Patterson", email: "felix.patterson@email.co.uk", location: "Stockport, SK1 1AA", joinedDate: "2024-08-19", role: "Driver", status: "Active" },
    { id: "USR-082", name: "Beatrice Fletcher", email: "beatrice.fletcher@email.co.uk", location: "Rochdale, OL16 1AA", joinedDate: "2024-08-18", role: "Driver", status: "Suspended" },
    { id: "USR-083", name: "Tobias Boyd", email: "tobias.boyd@email.co.uk", location: "Oldham, OL1 1AA", joinedDate: "2024-08-18", role: "Driver", status: "Active" },
    { id: "USR-084", name: "Imogen Palmer", email: "imogen.palmer@email.co.uk", location: "Burnley, BB11 1AA", joinedDate: "2024-08-17", role: "Driver", status: "Active" },
    { id: "USR-085", name: "Caleb Riley", email: "caleb.riley@email.co.uk", location: "Blackburn, BB1 1AA", joinedDate: "2024-08-17", role: "Driver", status: "Active" },
    { id: "USR-086", name: "Darcie Ford", email: "darcie.ford@email.co.uk", location: "Huddersfield, HD1 1AA", joinedDate: "2024-08-16", role: "Driver", status: "Active" },
    { id: "USR-087", name: "Elliot Pierce", email: "elliot.pierce@email.co.uk", location: "Bradford, BD1 1AA", joinedDate: "2024-08-16", role: "Driver", status: "Active" },
    { id: "USR-088", name: "Iris Berry", email: "iris.berry@email.co.uk", location: "Wakefield, WF1 1AA", joinedDate: "2024-08-15", role: "Driver", status: "Active" },
    { id: "USR-089", name: "Nathan Lane", email: "nathan.lane@email.co.uk", location: "Doncaster, DN1 1AA", joinedDate: "2024-08-15", role: "Driver", status: "Active" },
    { id: "USR-090", name: "Bonnie Francis", email: "bonnie.francis@email.co.uk", location: "Rotherham, S60 1AA", joinedDate: "2024-08-14", role: "Driver", status: "Suspended" },
    { id: "USR-091", name: "Austin Grant", email: "austin.grant@email.co.uk", location: "Barnsley, S70 1AA", joinedDate: "2024-08-14", role: "Driver", status: "Active" },
    { id: "USR-092", name: "Ivy Chapman", email: "ivy.chapman@email.co.uk", location: "Chesterfield, S40 1AA", joinedDate: "2024-08-13", role: "Driver", status: "Active" },
    { id: "USR-093", name: "Jayden Wells", email: "jayden.wells@email.co.uk", location: "Mansfield, NG18 1AA", joinedDate: "2024-08-13", role: "Driver", status: "Active" },
    { id: "USR-094", name: "Orla Hunt", email: "orla.hunt@email.co.uk", location: "Grimsby, DN31 1AA", joinedDate: "2024-08-12", role: "Driver", status: "Active" },
    { id: "USR-095", name: "Blake Douglas", email: "blake.douglas@email.co.uk", location: "Scunthorpe, DN15 1AA", joinedDate: "2024-08-12", role: "Driver", status: "Active" },
    { id: "USR-096", name: "Lottie Simpson", email: "lottie.simpson@email.co.uk", location: "Telford, TF1 1AA", joinedDate: "2024-08-11", role: "Driver", status: "Active" },
    { id: "USR-097", name: "Ezra Ferguson", email: "ezra.ferguson@email.co.uk", location: "Nuneaton, CV10 1AA", joinedDate: "2024-08-11", role: "Driver", status: "Active" },
    { id: "USR-098", name: "Willow Davies", email: "willow.davies@email.co.uk", location: "Eastbourne, BN21 1AA", joinedDate: "2024-08-10", role: "Driver", status: "Suspended" },
    { id: "USR-099", name: "Kai Henderson", email: "kai.henderson@email.co.uk", location: "Hastings, TN34 1AA", joinedDate: "2024-08-10", role: "Driver", status: "Active" },
  ];

export const adminSuppliers = [
    { id: "SUP-001", name: "AutoParts Direct Ltd", location: "London", rating: 4.8, quotes: 234, status: "Active", joined: "2023-08-12", categories: ["Engine", "Brakes"], email: "contact@autopartsdirect.co.uk", phone: "020 1234 5678", businessAddress: "45 High Street, London, E1 6AN", registrationNumber: "12345678", vatNumber: "GB123456789", yearsInBusiness: 8, description: "Leading supplier of quality automotive parts with 8 years of experience serving the UK market.", appliedDate: "2023-07-15", docsComplete: true },
    { id: "SUP-002", name: "BrakeMasters UK", location: "Manchester", rating: 4.9, quotes: 189, status: "Active", joined: "2023-09-20", categories: ["Brakes", "Suspension"], email: "info@brakemasters.co.uk", phone: "0161 234 5678", businessAddress: "78 Market Street, Manchester, M1 1PW", registrationNumber: "87654321", vatNumber: "GB987654321", yearsInBusiness: 12, description: "Specialist brake and suspension parts supplier with nationwide delivery.", appliedDate: "2023-08-28", docsComplete: true },
    { id: "SUP-003", name: "Engine Experts Ltd", location: "Birmingham", rating: 4.7, quotes: 156, status: "Active", joined: "2023-10-05", categories: ["Engine", "Electrical"], email: "sales@engineexperts.co.uk", phone: "0121 345 6789", businessAddress: "23 Station Road, Birmingham, B2 4QA", registrationNumber: "23456789", vatNumber: "GB234567890", yearsInBusiness: 15, description: "Expert engine and electrical parts supplier with comprehensive stock.", appliedDate: "2023-09-12", docsComplete: true },
    { id: "SUP-004", name: "CarCare Solutions", location: "Leeds", rating: 4.6, quotes: 145, status: "Active", joined: "2023-11-15", categories: ["Bodywork", "Interior"], email: "hello@carcaresolutions.co.uk", phone: "0113 456 7890", businessAddress: "56 Main Avenue, Leeds, LS1 5DL", registrationNumber: "34567890", vatNumber: "GB345678901", yearsInBusiness: 6, description: "Quality bodywork and interior parts for all vehicle makes and models.", appliedDate: "2023-10-20", docsComplete: true },
    { id: "SUP-005", name: "Suspension Pro", location: "Bristol", rating: 4.8, quotes: 178, status: "Active", joined: "2024-01-08", categories: ["Suspension", "Brakes"], email: "contact@suspensionpro.co.uk", phone: "0117 567 8901", businessAddress: "89 Park Lane, Bristol, BS1 5TR", registrationNumber: "45678901", vatNumber: "GB456789012", yearsInBusiness: 10, description: "Professional suspension and brake specialists with fast delivery service.", appliedDate: "2023-12-10", docsComplete: true },
    { id: "SUP-006", name: "Transmission Specialists", location: "Glasgow", rating: 4.7, quotes: 167, status: "Active", joined: "2024-01-22", categories: ["Engine", "Transmission"], email: "info@transmissionspecialists.co.uk", phone: "0141 234 5678", businessAddress: "34 Industrial Way, Glasgow, G2 1AA", registrationNumber: "56789012", vatNumber: "GB567890123", yearsInBusiness: 9, description: "Specialist transmission and engine parts with expert technical support.", appliedDate: "2023-12-28", docsComplete: true },
    { id: "SUP-007", name: "EcoParts Ltd", location: "Edinburgh", rating: 4.9, quotes: 201, status: "Active", joined: "2024-02-05", categories: ["Electrical", "Engine"], email: "sales@ecoparts.co.uk", phone: "0131 345 6789", businessAddress: "12 Green Street, Edinburgh, EH2 2BB", registrationNumber: "67890123", vatNumber: "GB678901234", yearsInBusiness: 5, description: "Eco-friendly and sustainable automotive parts supplier.", appliedDate: "2024-01-10", docsComplete: true },
    { id: "SUP-008", name: "Performance Parts Pro", location: "Liverpool", rating: 4.6, quotes: 134, status: "Active", joined: "2024-02-18", categories: ["Engine", "Brakes"], email: "contact@performancepartspro.co.uk", phone: "0151 456 7890", businessAddress: "67 Motor Lane, Liverpool, L2 3CC", registrationNumber: "78901234", vatNumber: "GB789012345", yearsInBusiness: 7, description: "High-performance parts for all makes and models.", appliedDate: "2024-01-25", docsComplete: true },
    { id: "SUP-009", name: "Classic Car Components", location: "Oxford", rating: 4.8, quotes: 198, status: "Active", joined: "2024-03-02", categories: ["Bodywork", "Interior"], email: "hello@classiccarcomponents.co.uk", phone: "01865 567 8901", businessAddress: "89 Heritage Road, Oxford, OX3 4DD", registrationNumber: "89012345", vatNumber: "GB890123456", yearsInBusiness: 14, description: "Specialist in classic and vintage car parts.", appliedDate: "2024-02-08", docsComplete: true },
    { id: "SUP-010", name: "TyreTech Solutions", location: "Cardiff", rating: 4.7, quotes: 176, status: "Active", joined: "2024-03-15", categories: ["Suspension", "Brakes"], email: "info@tyretech.co.uk", phone: "029 2034 5678", businessAddress: "45 Valley Street, Cardiff, CF4 5EE", registrationNumber: "90123456", vatNumber: "GB901234567", yearsInBusiness: 11, description: "Comprehensive tyre and suspension solutions.", appliedDate: "2024-02-20", docsComplete: true },
    { id: "SUP-011", name: "AutoElectric UK", location: "Newcastle", rating: 4.9, quotes: 212, status: "Active", joined: "2024-03-28", categories: ["Electrical", "Interior"], email: "sales@autoelectric.co.uk", phone: "0191 678 9012", businessAddress: "23 Circuit Avenue, Newcastle, NE5 6FF", registrationNumber: "01234567", vatNumber: "GB012345678", yearsInBusiness: 8, description: "Electrical systems and interior components specialist.", appliedDate: "2024-03-05", docsComplete: true },
    { id: "SUP-012", name: "BodyShop Supplies", location: "Southampton", rating: 4.6, quotes: 143, status: "Active", joined: "2024-04-10", categories: ["Bodywork", "Interior"], email: "contact@bodyshopsupplies.co.uk", phone: "023 8012 3456", businessAddress: "78 Marine Drive, Southampton, SO6 7GG", registrationNumber: "12345670", vatNumber: "GB123456780", yearsInBusiness: 6, description: "Complete bodywork and paint supplies for professionals.", appliedDate: "2024-03-18", docsComplete: true },
    { id: "SUP-013", name: "Diesel Parts Direct", location: "Nottingham", rating: 4.8, quotes: 187, status: "Active", joined: "2024-04-23", categories: ["Engine", "Electrical"], email: "info@dieselpartsdirect.co.uk", phone: "0115 234 5678", businessAddress: "34 Commerce Road, Nottingham, NG7 8HH", registrationNumber: "23456701", vatNumber: "GB234567801", yearsInBusiness: 13, description: "Specialist diesel engine parts and components.", appliedDate: "2024-04-01", docsComplete: true },
    { id: "SUP-014", name: "Continental Auto Parts", location: "Leicester", rating: 4.7, quotes: 165, status: "Active", joined: "2024-05-06", categories: ["Engine", "Brakes"], email: "sales@continentalauto.co.uk", phone: "0116 345 6789", businessAddress: "56 International Way, Leicester, LE8 9II", registrationNumber: "34567012", vatNumber: "GB345670812", yearsInBusiness: 10, description: "European and continental car parts specialist.", appliedDate: "2024-04-15", docsComplete: true },
    { id: "SUP-015", name: "QuickFit Components", location: "Sheffield", rating: 4.9, quotes: 223, status: "Active", joined: "2024-05-19", categories: ["Suspension", "Brakes"], email: "contact@quickfit.co.uk", phone: "0114 456 7890", businessAddress: "12 Speed Lane, Sheffield, S9 0JJ", registrationNumber: "45670123", vatNumber: "GB456701823", yearsInBusiness: 7, description: "Fast-fit components with same-day delivery options.", appliedDate: "2024-04-28", docsComplete: true },
    { id: "SUP-016", name: "Heritage Motors Supply", location: "Cambridge", rating: 4.6, quotes: 131, status: "Active", joined: "2024-06-01", categories: ["Engine", "Interior"], email: "hello@heritagemotors.co.uk", phone: "01223 567 8901", businessAddress: "89 Scholar Road, Cambridge, CB0 1KK", registrationNumber: "56701234", vatNumber: "GB567012834", yearsInBusiness: 16, description: "Classic and modern parts with heritage expertise.", appliedDate: "2024-05-10", docsComplete: true },
    { id: "SUP-017", name: "Commercial Vehicle Parts", location: "Portsmouth", rating: 4.8, quotes: 194, status: "Active", joined: "2024-06-14", categories: ["Engine", "Suspension"], email: "info@commercialvehicleparts.co.uk", phone: "023 9234 5678", businessAddress: "45 Dock Street, Portsmouth, PO1 2LL", registrationNumber: "67012345", vatNumber: "GB670123845", yearsInBusiness: 9, description: "Specialist in commercial and heavy vehicle parts.", appliedDate: "2024-05-23", docsComplete: true },
    { id: "SUP-018", name: "Motorsport Components", location: "Coventry", rating: 4.7, quotes: 172, status: "Active", joined: "2024-06-27", categories: ["Engine", "Brakes"], email: "sales@motorsportcomponents.co.uk", phone: "024 7678 9012", businessAddress: "23 Racing Circuit, Coventry, CV2 3MM", registrationNumber: "70123456", vatNumber: "GB701234856", yearsInBusiness: 11, description: "High-performance motorsport parts and accessories.", appliedDate: "2024-06-05", docsComplete: true },
    { id: "SUP-019", name: "Green Auto Solutions", location: "Brighton", rating: 4.9, quotes: 208, status: "Active", joined: "2024-07-10", categories: ["Electrical", "Engine"], email: "contact@greenautosolutions.co.uk", phone: "01273 890 1234", businessAddress: "67 Coastal Road, Brighton, BN3 4NN", registrationNumber: "01234568", vatNumber: "GB012345687", yearsInBusiness: 5, description: "Sustainable and eco-friendly automotive solutions.", appliedDate: "2024-06-18", docsComplete: true },
    { id: "SUP-020", name: "Precision Engineering Parts", location: "Norwich", rating: 4.6, quotes: 148, status: "Active", joined: "2024-07-23", categories: ["Engine", "Suspension"], email: "info@precisionengineering.co.uk", phone: "01603 012 3456", businessAddress: "34 Technical Avenue, Norwich, NR4 5OO", registrationNumber: "12345608", vatNumber: "GB123456087", yearsInBusiness: 12, description: "Precision-engineered parts for demanding applications.", appliedDate: "2024-07-01", docsComplete: true },
    { id: "SUP-021", name: "Budget Auto Parts", location: "Plymouth", rating: 4.7, quotes: 181, status: "Active", joined: "2024-08-05", categories: ["Brakes", "Suspension"], email: "sales@budgetautoparts.co.uk", phone: "01752 123 4567", businessAddress: "78 Harbour Way, Plymouth, PL5 6PP", registrationNumber: "23456018", vatNumber: "GB234560187", yearsInBusiness: 8, description: "Affordable quality parts without compromise.", appliedDate: "2024-07-14", docsComplete: true },
    { id: "SUP-022", name: "Premium Vehicle Components", location: "Derby", rating: 4.8, quotes: 195, status: "Active", joined: "2024-08-18", categories: ["Interior", "Bodywork"], email: "contact@premiumvehicle.co.uk", phone: "01332 234 5678", businessAddress: "12 Luxury Lane, Derby, DE6 7QQ", registrationNumber: "34560128", vatNumber: "GB345601287", yearsInBusiness: 10, description: "Premium-grade vehicle components and accessories.", appliedDate: "2024-07-27", docsComplete: true },
    { id: "SUP-023", name: "Fleet Parts Specialist", location: "Wolverhampton", rating: 4.9, quotes: 217, status: "Active", joined: "2024-09-01", categories: ["Engine", "Electrical"], email: "info@fleetparts.co.uk", phone: "01902 345 6789", businessAddress: "56 Industrial Park, Wolverhampton, WV7 8RR", registrationNumber: "45601238", vatNumber: "GB456012387", yearsInBusiness: 14, description: "Fleet management and bulk supply specialist.", appliedDate: "2024-08-10", docsComplete: true },
    { id: "SUP-024", name: "Hybrid Tech Parts", location: "Reading", rating: 4.7, quotes: 169, status: "Active", joined: "2024-09-14", categories: ["Electrical", "Engine"], email: "sales@hybridtechparts.co.uk", phone: "0118 456 7890", businessAddress: "89 Future Drive, Reading, RG8 9SS", registrationNumber: "56012348", vatNumber: "GB560123487", yearsInBusiness: 6, description: "Specialist in hybrid and electric vehicle components.", appliedDate: "2024-08-23", docsComplete: true },
    { id: "SUP-025", name: "Classic British Motors", location: "Bath", rating: 4.8, quotes: 192, status: "Active", joined: "2024-09-27", categories: ["Engine", "Interior"], email: "contact@classicbritish.co.uk", phone: "01225 567 8901", businessAddress: "23 Heritage Street, Bath, BA9 0TT", registrationNumber: "60123458", vatNumber: "GB601234587", yearsInBusiness: 18, description: "Authentic British classic car parts and restoration.", appliedDate: "2024-09-05", docsComplete: true },
    { id: "SUP-026", name: "4x4 Parts Centre", location: "Exeter", rating: 4.6, quotes: 156, status: "Active", joined: "2024-10-10", categories: ["Suspension", "Engine"], email: "info@4x4parts.co.uk", phone: "01392 678 9012", businessAddress: "45 Off-Road Way, Exeter, EX0 1UU", registrationNumber: "01234598", vatNumber: "GB012345987", yearsInBusiness: 9, description: "Specialist 4x4 and off-road vehicle parts.", appliedDate: "2024-09-18", docsComplete: true },
    { id: "SUP-027", name: "Van Parts Direct", location: "Stoke-on-Trent", rating: 4.9, quotes: 226, status: "Active", joined: "2024-10-23", categories: ["Engine", "Brakes"], email: "sales@vanpartsdirect.co.uk", phone: "01782 789 0123", businessAddress: "67 Commercial Road, Stoke-on-Trent, ST1 2VV", registrationNumber: "12345098", vatNumber: "GB123450987", yearsInBusiness: 11, description: "Complete van parts and accessories supplier.", appliedDate: "2024-10-01", docsComplete: true },
    { id: "SUP-028", name: "European Car Specialists", location: "Milton Keynes", rating: 4.7, quotes: 173, status: "Active", joined: "2024-11-05", categories: ["Electrical", "Brakes"], email: "contact@europeancar.co.uk", phone: "01908 890 1234", businessAddress: "34 Continental Avenue, Milton Keynes, MK2 3WW", registrationNumber: "23450198", vatNumber: "GB234501987", yearsInBusiness: 13, description: "European vehicle parts import specialist.", appliedDate: "2024-10-14", docsComplete: true },
    { id: "SUP-029", name: "Performance Tuning Parts", location: "Bournemouth", rating: 4.8, quotes: 189, status: "Active", joined: "2024-11-18", categories: ["Engine", "Electrical"], email: "info@performancetuning.co.uk", phone: "01202 012 3456", businessAddress: "78 Speed Street, Bournemouth, BH3 4XX", registrationNumber: "34501298", vatNumber: "GB345012987", yearsInBusiness: 7, description: "Performance tuning and modification parts.", appliedDate: "2024-10-27", docsComplete: true },
    { id: "SUP-030", name: "Safety First Auto Parts", location: "Sunderland", rating: 4.9, quotes: 211, status: "Active", joined: "2024-12-01", categories: ["Brakes", "Suspension"], email: "sales@safetyfirst.co.uk", phone: "0191 123 4567", businessAddress: "12 Protection Road, Sunderland, SR4 5YY", registrationNumber: "45012398", vatNumber: "GB450123987", yearsInBusiness: 10, description: "Safety-focused brake and suspension specialists.", appliedDate: "2024-11-10", docsComplete: true },
  ];

export const adminPendingSuppliers = [
    { id: "SUP-P01", name: "Quality Motors Ltd", location: "Liverpool", email: "info@qualitymotors.co.uk", phone: "0151 234 5678", categories: ["Engine", "Brakes", "Suspension"], appliedDate: "2024-10-25", docsComplete: true, businessAddress: "12 Commercial Road, Liverpool, L1 2AB", registrationNumber: "56789012", vatNumber: "GB567890123", yearsInBusiness: 5, description: "Established supplier specialising in quality engine and brake components." },
    { id: "SUP-P02", name: "Fast Parts Supply", location: "Sheffield", email: "sales@fastparts.co.uk", phone: "0114 345 6789", categories: ["Electrical", "Interior"], appliedDate: "2024-10-24", docsComplete: false, businessAddress: "34 Industrial Estate, Sheffield, S1 3CD", registrationNumber: "67890123", vatNumber: "GB678901234", yearsInBusiness: 3, description: "Fast delivery electrical and interior parts supplier." },
    { id: "SUP-P03", name: "Premium Auto Parts", location: "Newcastle", email: "contact@premiumauto.co.uk", phone: "0191 456 7890", categories: ["Bodywork", "Engine"], appliedDate: "2024-10-23", docsComplete: true, businessAddress: "67 Trading Way, Newcastle, NE1 4EF", registrationNumber: "78901234", vatNumber: "GB789012345", yearsInBusiness: 7, description: "Premium quality bodywork and engine parts distributor." },
  ];

export const adminAbuseReports = [
    { id: "REP-001", reportedBy: "John Smith", reportedUser: "AutoParts Direct Ltd", reason: "Late delivery and poor communication with customer", status: "Under Review", date: "2024-10-26", severity: "Low" },
    { id: "REP-002", reportedBy: "Sarah Jones", reportedUser: "BrakeMasters UK", reason: "Poor quality parts that failed after installation", status: "Resolved", date: "2024-10-25", severity: "Medium" },
    { id: "REP-003", reportedBy: "Mike Brown", reportedUser: "Engine Experts Ltd", reason: "Incorrect parts sent despite correct specification", status: "Under Review", date: "2024-10-24", severity: "High" },
  ];

export const adminWeeklyData = [
    { week: "Week 1", users: 245, suppliers: 12, quotes: 156 },
    { week: "Week 2", users: 298, suppliers: 15, quotes: 189 },
    { week: "Week 3", users: 312, suppliers: 18, quotes: 203 },
    { week: "Week 4", users: 356, suppliers: 21, quotes: 234 },
  ];

export const adminCategoryData = [
    { category: "Engine", requests: 234, avgPrice: 245 },
    { category: "Brakes", requests: 189, avgPrice: 128 },
    { category: "Suspension", requests: 156, avgPrice: 198 },
    { category: "Electrical", requests: 145, avgPrice: 89 },
    { category: "Bodywork", requests: 98, avgPrice: 312 },
  ];

export const adminRevenueData = [
    { week: "Week 1", commission: 2450, fees: 890 },
    { week: "Week 2", commission: 2980, fees: 1020 },
    { week: "Week 3", commission: 3120, fees: 1150 },
    { week: "Week 4", commission: 3560, fees: 1280 },
  ];

export const adminInquiries = [
    { 
      id: "INQ-001", 
      name: "Sarah Thompson", 
      email: "sarah.thompson@email.co.uk", 
      subject: "Question about supplier verification", 
      message: "Hello, I would like to know more about how you verify your suppliers. What checks do you perform before approving a new supplier on the platform?",
      date: "2024-11-01",
      time: "14:32",
      status: "New",
      category: "General Enquiry"
    },
    { 
      id: "INQ-002", 
      name: "Michael Brown", 
      email: "michael.brown@email.co.uk", 
      subject: "Partnership opportunity", 
      message: "I represent a large automotive parts distributor and we're interested in partnering with your platform. Could we arrange a call to discuss this further?",
      date: "2024-10-31",
      time: "10:15",
      status: "Responded",
      category: "Business Partnership"
    },
    { 
      id: "INQ-003", 
      name: "Emma Wilson", 
      email: "emma.wilson@email.co.uk", 
      subject: "Technical support needed", 
      message: "I'm having trouble uploading photos when requesting a quote. The upload button doesn't seem to be working properly. Can you help?",
      date: "2024-10-30",
      time: "16:48",
      status: "New",
      category: "Technical Support"
    },
    { 
      id: "INQ-004", 
      name: "James Parker", 
      email: "james.parker@email.co.uk", 
      subject: "Feedback on platform", 
      message: "Just wanted to say the platform is brilliant! Found exactly what I needed within hours. The comparison feature is especially useful. Keep up the great work!",
      date: "2024-10-29",
      time: "09:22",
      status: "Responded",
      category: "Feedback"
    },
    { 
      id: "INQ-005", 
      name: "Charlotte Davies", 
      email: "charlotte.davies@email.co.uk", 
      subject: "Delivery tracking question", 
      message: "How can I track my delivery once I've purchased a part? I can't seem to find the tracking information in my account.",
      date: "2024-10-28",
      time: "11:55",
      status: "New",
      category: "General Enquiry"
    },
    { 
      id: "INQ-006", 
      name: "Robert Anderson", 
      email: "robert.anderson@email.co.uk", 
      subject: "Request for invoice", 
      message: "Could you please send me a VAT invoice for my recent purchase (Order #12345)? I need it for my business records.",
      date: "2024-10-27",
      time: "13:40",
      status: "Responded",
      category: "Billing"
    },
    { 
      id: "INQ-007", 
      name: "Lucy Martin", 
      email: "lucy.martin@email.co.uk", 
      subject: "Account deletion request", 
      message: "I would like to delete my account and all associated data. Please confirm how to proceed with this request.",
      date: "2024-10-26",
      time: "15:18",
      status: "New",
      category: "Account Management"
    },
    { 
      id: "INQ-008", 
      name: "David Taylor", 
      email: "david.taylor@email.co.uk", 
      subject: "Question about returns policy", 
      message: "What is your returns policy if the part I receive is not the correct one? Do suppliers handle returns individually or is there a platform-wide policy?",
      date: "2024-10-25",
      time: "08:45",
      status: "Responded",
      category: "Returns & Refunds"
    }
  ];
