export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
  },

  website: {
    vehicleLookup: '/vehicle/lookup',
    partsRequest: '/parts/request',
    partsCategories: '/parts/categories',
    partsFeatured: '/parts/featured',
    partsSearch: '/parts/search',
    contact: '/contact',
    newsletterSubscribe: '/newsletter/subscribe',
    suppliersFeatured: '/suppliers/featured',
    suppliersSearch: '/suppliers/search',
    supplierById: (id: string) => `/suppliers/${id}`,
  },

  admin: {
    dashboardStats: '/admin/dashboard/stats',
    users: '/admin/users',
    userById: (id: string) => `/admin/users/${id}`,
    userSuspend: (id: string) => `/admin/users/${id}/suspend`,
    userActivate: (id: string) => `/admin/users/${id}/activate`,
    customers: '/admin/customers',
    suppliers: '/admin/suppliers',
    supplierById: (id: string) => `/admin/suppliers/${id}`,
    supplierVerify: (id: string) => `/admin/suppliers/${id}/verify`,
    enquiries: '/admin/enquiries',
    enquiryById: (id: string) => `/admin/enquiries/${id}`,
    orders: '/admin/orders',
    reports: '/admin/reports',
    export: '/admin/export',
    analytics: '/admin/analytics',
    settings: '/admin/settings',
    logs: '/admin/logs',
  },

  customer: {
    requests: '/customer/requests',
    requestById: (id: string) => `/customer/requests/${id}`,
    quotes: '/customer/quotes',
    quoteAccept: (id: string) => `/customer/quotes/${id}/accept`,
    quoteReject: (id: string) => `/customer/quotes/${id}/reject`,
    conversations: '/customer/conversations',
    conversationMessages: (id: string) => `/customer/conversations/${id}/messages`,
    conversationRead: (id: string) => `/customer/conversations/${id}/read`,
    orders: '/customer/orders',
    orderById: (id: string) => `/customer/orders/${id}`,
    orderCancel: (id: string) => `/customer/orders/${id}/cancel`,
    orderReview: (id: string) => `/customer/orders/${id}/review`,
    notifications: '/customer/notifications',
    notificationRead: (id: string) => `/customer/notifications/${id}/read`,
    notificationsReadAll: '/customer/notifications/read-all',
    profile: '/customer/profile',
    profileAddress: '/customer/profile/address',
  },

  supplier: {
    onboarding: '/supplier/onboarding',
    dashboardStats: '/supplier/dashboard/stats',
    enquiries: '/supplier/enquiries',
    enquiryById: (id: string) => `/supplier/enquiries/${id}`,
    quotes: '/supplier/quotes',
    quoteById: (id: string) => `/supplier/quotes/${id}`,
    quoteWithdraw: (id: string) => `/supplier/quotes/${id}/withdraw`,
    conversations: '/supplier/conversations',
    conversationMessages: (id: string) => `/supplier/conversations/${id}/messages`,
    orders: '/supplier/orders',
    orderStatus: (id: string) => `/supplier/orders/${id}/status`,
    profile: '/supplier/profile',
    profileHours: '/supplier/profile/hours',
    documents: '/supplier/documents',
    analytics: '/supplier/analytics',
    reviews: '/supplier/reviews',
  },
} as const;

export type ApiRoutes = typeof API_ROUTES;
